menu:
- {name: 'projects', url: '/projects'}
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Liming Tan', title: 'Professor',type: 'Principle Investigator', department: 'Brain Insitute', institution: 'Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences', email: 'lm.tan@siat.ac.cn', image: 'assets/img/limingtan_half.png',description: 'Genetics, Plasticity and Vision',googleScholar: "https://scholar.google.com/citations?user=mGhI_w4AAAAJ&hl=en",orcid: "https://orcid.org/0000-0002-7034-0321",neurotree: "https://neurotree.org/beta/tree.php?pid=746386" }
- {name: 'Lin Wang', title: 'Research Assistant',type: 'Research Staff',department: 'Brain Insitute', institution: 'Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences', email: 'l.wang@siat.ac.cn', image: 'assets/img/wanglin.jpg',description: 'Single cell spatial genomics, Computational Biology'}
- {name: 'Chunyun Jia', title: 'Research Assistant',type: 'Research Staff', department: 'Brain Insitute', institution: 'Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences',  email: 'cy.jia1@siat.ac.cn', image: 'assets/img/jiachunyun.jpg', description: 'Neuronal tracing, Neuroplasticity Research'}
- {name: 'Xiang Gao', title: 'Assistant Professor',type: 'Principle Investigator', department: 'Brain Insitute', institution: 'Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences',  email: 'x.gao3@siat.ac.cn', image: 'assets/img/gaoxiang.jpg', description: 'Single cell genomics, Genome-wide association study'}
- {name: 'Chuying Zhou', title: 'Postdoc',type: 'Postdoctoral Scholars', department: 'Brain Insitute', institution: 'Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences',  email: 'cy.zhou2@siat.ac.cn', image: 'assets/img/zhouchuying.jpg', description: 'Neuroplasticity in the development of visual circuit'}
- {name: 'Jing Zhu', title: 'Postdoc',type: 'Postdoctoral Scholars', department: 'Brain Insitute', institution: 'Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences',  email: 'j.zhu2@siat.ac.cn', image: 'assets/img/zhujing.jpg', description: 'Spatial transcriptomics and Neurobehavioral Research'}
- {name: 'Yao Ge', title: 'PhD student',type: 'Graduate Students', department: 'Brain Insitute', institution: 'Southeast University & Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences',  email: 'y.ge@siat.ac.cn', image: 'assets/img/geyao.jpg',description: 'Neuropixels, Animal behavior research' }
- {name: 'Xinqi Li', title: 'MS student',type: 'Graduate Students', department: 'Brain Insitute', institution: 'University of Science and Technology of China & Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences',  email: '2010667442@qq.com', image: 'assets/img/lixinqi.jpg',description: 'Retinotopic mapping' }
- {name: 'jingxi Zhao', title: 'MS student',type: 'Graduate Students', department: 'Brain Insitute', institution: 'Macau University of Science and Technology & Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences',  email: 'jingxizhao0926@gmail.com', image: 'assets/img/zhaojingxi.jpg',description: 'Glaucoma and Brain Research' }

alumni:
- {name: '*', title: '*',type: 'Principle Investigator',year: '*',position: '*',career: '*',department: 'Brain Insitute', institution: 'Shenzhen Institute of Advanced Technology, Chinese Academy of Sciences', email: 'lm.tan@siat.ac.cn', image: 'assets/img/limingtan_half.jpg',description: 'Genetics, Plasticity and Vision'}

projects:
- {name: 'Coming Up Soon', url: 'vector-calculus'}
- {name: 'Coming Up Soon', url: 'quantum-mechanics'}
- {name: 'Coming Up Soon', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/orgs/Tan-Lab-SIAT/repositories'}


contacts:
- {name: 'Dr. Liming Tan', title: 'Principle Investigator', department: 'Brain Institute', institution: 'Shenzhen Institute of Advanced Technology', email: 'lm.tan@siat.ac.cn', image: 'assets/img/naochuang.webp'}

icon:
  googleScholar: "/assets/img/scholar_icon.png"
  orcid: "/assets/img/orcid_icon.svg"
  neurotree: "/assets/img/tree_icon.jpg"
